global:
  scrape_interval:     5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: airflow
    scheme: http
    metrics_path: metrics
    static_configs:
      - targets: ['44.229.122.134:9102']
        labels:
          airflow_id: 'airflow'

  - job_name: node
    static_configs:
      - targets: ['44.229.122.134:9200']
