version: "3.8"
services:

  web:
    build: 
      context: ../../CorpAnalytica_Web
    command: python3 manage.py runserver 0.0.0.0:8000 
      # - gunicorn CorpAnalytica_Web.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224    #서버 주소 적어야함!!!!!!!!!!!
        tag: web.access
    
    volumes:
      - ../../CorpAnalytica_Web:/app

  fluentd:
    build: ../../fluentd
    container_name: fluentd
    volumes:
      - ../../fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - elastic


  prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - ../../data-monitoring/configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9092:9090
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    ports:
      - 3000:3000
  

volumes:
  prometheus_data:
  grafana_data:
networks:
  elastic:
    driver: bridge
