version: '3.8'
services:
  web:
    build: 
      context: ../../CorpAnalytica_Web
    command: gunicorn CorpAnalytica_Web.wsgi:application --bind 0.0.0.0:8000
      # - python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    # expose:
    #   - "8000"
    volumes:
      - ../../CorpAnalytica_Web:/app
  
  nginx:
    image:
      nginx:latest
    ports:
      - "70:80"
    volumes:
      # - ../../CorpAnalytica_Web:/app
      # - ../../CorpAnalytica_Web/nginx:/etc/nginx/conf.d
      # - ../../CorpAnalytica_Web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../CorpAnalytica_Web/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web


  # statsd-exporter:
  #   image: prom/statsd-exporter:v0.21.0
  #   volumes:
  #     - ../../data-monitoring/configs/statsd.yaml:/home/statsd-mapping-configs.yaml
  #   entrypoint: ["/bin/sh", "-c", "--"]
  #   command: ["statsd_exporter --log.level debug --statsd.mapping-config=/home/statsd-mapping-configs.yaml"]
  #   ports:
  #     - 9102:9102   # scrape port
  #     - 9125:9125   # ingest port
  #   restart: always

  # node-exporter:
  #   image: prom/node-exporter
  #   ports:
  #     - 9200:9100
  #   # restarts: always


  prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - ../../data-monitoring/configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9092:9090
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    ports:
      - 3000:3000

volumes:
  prometheus_data:
  grafana_data:
