# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the "main" branch.
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create an ECR repository to store your images.
#    For example: `aws ecr create-repository --repository-name my-ecr-repo --region us-east-2`.
#    Replace the value of the `ECR_REPOSITORY` environment variable in the workflow below with your repository's name.
#    Replace the value of the `AWS_REGION` environment variable in the workflow below with your repository's region.
#
# 2. Create an ECS task definition, an ECS cluster, and an ECS service.
#    For example, follow the Getting Started guide on the ECS console:
#      https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2#/firstRun
#    Replace the value of the `ECS_SERVICE` environment variable in the workflow below with the name you set for the Amazon ECS service.
#    Replace the value of the `ECS_CLUSTER` environment variable in the workflow below with the name you set for the cluster.
#
# 3. Store your ECS task definition as a JSON file in your repository.
#    The format should follow the output of `aws ecs register-task-definition --generate-cli-skeleton`.
#    Replace the value of the `ECS_TASK_DEFINITION` environment variable in the workflow below with the path to the JSON file.
#    Replace the value of the `CONTAINER_NAME` environment variable in the workflow below with the name of the container
#    in the `containerDefinitions` section of the task definition.
#
# 4. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.

name: Deploy to Amazon ECS

# on:
#   push:
#     branches: [ "main" ]

env:
  AWS_REGION: us-west-2                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: de-4-3-airflow          # set this to your Amazon ECR repository name
  ECS_CLUSTER: de-4-3-ECScluster                 # set this to your Amazon ECS cluster name

  ECS_SERVICE_SCHEDULER: de-4-3-airflow-service-scheduler           # set this to your Amazon ECS service name
  ECS_SERVICE_WORKER: de-4-3-airflow-service-worker                 # set this to your Amazon ECS service name
  ECS_SERVICE_WEBSERVER: de-4-3-airflow-service-webserver                 # set this to your Amazon ECS service name
  
  ECS_TASK_DEFINITION_SCHEDULER: task-definition-scheduler.json # set this to the path to your Amazon ECS task definition
  ECS_TASK_DEFINITION_WORKER: task-definition-worker.json
  ECS_TASK_DEFINITION_WEBSERVER: task-definition-webserver.json

  CONTAINER_NAME_SCHEDULER: de-4-3-airflow-scheduler           # set this to the name of the container in the containerDefinitions section of your task definition
  CONTAINER_NAME_WORKER: de-4-3-airflow-worker           # set this to the name of the container in the containerDefinitions section of your task definition
  CONTAINER_NAME_WEBSERVER: de-4-3-airflow-webserver           # set this to the name of the container in the containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG airflow/
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition de-4-3-scheduler --query taskDefinition > task-definition-scheduler.json
        aws ecs describe-task-definition --task-definition de-4-3-worker --query taskDefinition > task-definition-worker.json
        aws ecs describe-task-definition --task-definition de-4-3-webserver --query taskDefinition > task-definition-webserver.json

    - name: Fill in the new image ID in the Amazon ECS task definition1
      id: task-def-scheduler
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION_SCHEDULER }}
        container-name: ${{ env.CONTAINER_NAME_SCHEDULER }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Fill in the new image ID in the Amazon ECS task definition2
      id: task-def-worker
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION_WORKER }}
        container-name: ${{ env.CONTAINER_NAME_WORKER }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Fill in the new image ID in the Amazon ECS task definition3
      id: task-def-webserver
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION_WEBSERVER }}
        container-name: ${{ env.CONTAINER_NAME_WEBSERVER }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition1
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-scheduler.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_SCHEDULER }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: false

    - name: Deploy Amazon ECS task definition2
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-worker.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_WORKER }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: false

    - name: Deploy Amazon ECS task definition3
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-webserver.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_WEBSERVER }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    # - name: Build, Push & Deploy
    #   run: |
    #     # Airflow
    #     aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE_SCHEDULER }} --force-new-deployment
    #     aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE_WORKER }} --force-new-deployment
    #     aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE_WEBSERVER }} --force-new-deployment
         
